name: CI

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - name: Test + Coverage + Benchmarks
        run: pnpm --filter reactflux test
